server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playground
    username: root
    password: root1234!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
      globally_quoted_identifiers: true

jwt:
  secretKey: "124215sdfhab8fr98234c2q4g87243cg"

  access:
    expiration: 1800000 # 30분 (1000L(ms -> s) * 60L(s -> m) * 30L)
    header: "Authorization"

  refresh:
    expiration: 1209600000 # 2주 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: "Authorization-refresh"
